In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv('MBA.csv')

df['admission'] = df['admission'].fillna(-1)
df['admission'] = df['admission'].replace("Admit",1)
df['admission'] = df['admission'].replace("Waitlist",0)

df = pd.get_dummies(df, columns=['gender', 'work_industry', 'major', 'race'], drop_first=False)


y = df.admission.values
X=df.drop(['admission'], axis='columns').values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size =0.30, random_state=42)


df.head()

[ 1 -1  1 ...  1 -1 -1]

/var/folders/d2/dbplq90x2ll9l3bnlgkbjtlr0000gn/T/ipykernel_95585/520007195.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['admission'] = df['admission'].replace("Waitlist",0)

,application_id,international,gpa,gmat,work_exp,admission,gender_Female,gender_Male,work_industry_CPG,work_industry_Consulting,...,work_industry_Retail,work_industry_Technology,major_Business,major_Humanities,major_STEM,race_Asian,race_Black,race_Hispanic,race_Other,race_White
0,1,False,3.30,620.0,3.0,1,True,False,False,False,...,False,False,True,False,False,True,False,False,False,False
1,2,False,3.28,680.0,5.0,-1,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,3,True,3.30,710.0,5.0,1,True,False,False,False,...,False,True,True,False,False,False,False,False,False,False
3,4,False,3.47,690.0,6.0,-1,False,True,False,False,...,False,True,False,False,True,False,True,False,False,False
4,5,False,3.35,590.0,5.0,-1,False,True,False,True,...,False,False,False,False,True,False,False,True,False,False

In [3]:
# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
params = { 'hidden_layer_sizes' : [20,10],
    'random_state' : 42,
    'max_iter' : 1000}

# Create an MLPClassifier model
mlp = MLPClassifier(**params)

# Train the model on the training data
mlp.fit(X_train, y_train)
 
# Make predictions on the test data
y_pred = mlp.predict(X_test)
 
# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Generate a classification report
class_report = classification_report(y_test, y_pred, zero_division=True)
print("Classification Report:\n", class_report)

Accuracy: 0.84
Classification Report:
               precision    recall  f1-score   support

          -1       0.84      1.00      0.91      1525
           0       1.00      0.00      0.00        35
           1       0.82      0.10      0.18       299

    accuracy                           0.84      1859
   macro avg       0.88      0.37      0.36      1859
weighted avg       0.84      0.84      0.78      1859